FROM node:10

MAINTAINER Christian Bergau <cbergau86@gmail.com>

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000
EXPOSE 3004
EXPOSE 8080
EXPOSE 35729

CMD ["npm", "start"]

USER node
